# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    trombi.form.registration:
        class: TrombiBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: trombi_user_registration }